{{- if .Values.enabled }}
apiVersion: v1
kind: {{ .Values.postgres.volume.pv.kind }}
metadata:
  name: {{ .Values.postgres.volume.pv.name }}
  labels:
    app: {{ .Values.app }}
    group: {{ .Values.group }}
spec:
  storageClassName: {{ .Values.postgres.volume.pv.storageClass }}
  capacity:
    storage: {{ .Values.postgres.volume.pv.storage }}
  accessModes:
    - {{ .Values.postgres.volume.pv.accessMode }}
  hostPath:
    path: {{ .Values.postgres.volume.pv.hostPath | quote }}
{{- end }}