{{- if .Values.enabled }}
apiVersion: v1
kind: {{ .Values.postgres.volume.pvc.kind }}
metadata:
  name: {{ .Values.postgres.volume.pvc.name }}
  labels:
    app: {{ .Values.app }}
    group: {{ .Values.group }}
spec:
  storageClassName: {{ .Values.postgres.volume.pvc.storageClass }}
  accessModes:
    - {{ .Values.postgres.volume.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.postgres.volume.pvc.storage }}
{{- end }}