{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secret.name }}
  labels:
    app: {{ .Values.app }}
    group: {{ .Values.group }}
type: {{ .Values.postgres.secret.type }}
data: 
{{- range .Values.postgres.secret.data }}
  {{ .key }}: {{ .value }}
{{- end}}
{{- end }}