{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}-service
  labels:
    app: {{ .Values.app }}
    group: {{ .Values.group }}
spec:
  type: {{ .Values.postgres.service.type }}
  selector:             
    app: {{ .Values.postgres.name }}
  ports:
    - port: {{ .Values.postgres.service.port }}       
      targetPort: {{ .Values.postgres.container.port }}
{{- end }}