kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: quiz-app
  name: deny-api-access
spec:
  podSelector:
    matchLabels:
      app: quiz-api
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: quiz-ui
    - namespaceSelector:
        matchLabels:
          namespace: quiz-app