version: "3.9"

services:
  frontend:
    container_name: quiz_app_frontend
    image: quiz_app_frontend:v1
    build:
      context: ./frontend
    ports:
      - 80:80
    expose:
      - 80
    depends_on:
      - quiz_app
    volumes:
      - "./frontend:/frontend"
      - /frontend/node_modules
    networks:
      - internalnet

  quiz_app:
    container_name: quiz_app
    image: efebeydogan01/quiz_app:1.0.0
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
      - FLASK_ENV=development
    depends_on:
      - flask_db
    volumes:
      - "./backend:/backend"
    networks:
      - internalnet
  
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internalnet

volumes:
  pgdata: {}

networks:
  internalnet:
    driver: bridge