namespaces:
  app: "quiz-app-helm"

serviceAccount:
  create: true # Specify whether a Service Account should be created
  name: "quiz-app" # The name of the Service Account
  annotations: {}


#####################
# Quiz DB
#####################
quizDB:
  app: quiz-app
  group: db

  postgres:
    name: quiz-db
    
    config:
      name: postgres-config
      data:
        - key: POSTGRES_DB
          value: postgres
        - key: POSTGRES_USER
          value: postgres
        - key: POSTGRES_PORT
          value: "5432"
        - key: POSTGRES_HOST
          value: quiz-db-service
    
    volume:
      pv:
        hostPath: "/opt/postgres/helm-data"
    
    secret:
      name: postgres-secret
      data:
        - key: POSTGRES_PASSWORD
          value: cG9zdGdyZXMK
    
    service:
      port: 5432
    
    networkpolicy:
      namespace: quiz-app-helm
      name: deny-database-access
      selectedPodApp: quiz-api

#####################
# Quiz API
#####################
quizAPI:
  labelapp: quiz-app
  group: backend

  genericApp:
    name: quiz-api

    container:
      image: localhost:32000/quiz-app
      port: 5000

    config:
      name: postgres-config

    secret:
      name: postgres-secret
      data:
        - key: POSTGRES_PASSWORD

    ingress:
      name: quiz-api
      annotations:
        - key: nginx.ingress.kubernetes.io/enable-cors
          value: "true"
        - key: nginx.ingress.kubernetes.io/cors-allow-methods
          value: "PUT, GET, POST, OPTIONS, DELETE"
        - key: nginx.ingress.kubernetes.io/cors-allow-origin
          value: "*"
        - key: nginx.ingress.kubernetes.io/cors-allow-credentials
          value: "true"
        - key: nginx.ingress.kubernetes.io/cors-allow-headers
          value: "DNT,X-CustomHeader,X-LANG,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Api-Key,X-Device-Id,Access-Control-Allow-Origin, Authorization, X-Access-Tokens"
      hosts:
        - host: api.quiz-app-helm.com
          paths: 
            - path: /
              pathType: Prefix
              backend:
                serviceName: quiz-api-service
                servicePort: 8080

#####################
# Quiz UI
#####################
quizUI:
  labelapp: quiz-app
  group: frontend

  genericApp:
    name: quiz-ui

    container:
      image: localhost:32000/quiz-ui
      port: 80
    
    ingress:
      name: quiz-ui
      hosts:
        - host: quiz-app-helm.com
          paths: 
            - path: /
              pathType: Prefix
              backend:
                serviceName: quiz-ui-service
                servicePort: 8080
    
    networkpolicy:
      namespace: quiz-app-helm
      name: ui-egress-policy
      selectedPodApp: quiz-api