apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-ui-canary
  labels:
    app: quiz-app
    group: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quiz-ui
      version: v7
  template:
    metadata:
      labels:
        app: quiz-ui
        group: frontend
        version: v7
    spec:
      containers:
        - name: quiz-ui-container
          image: "localhost:32000/quiz-ui:v7"
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD