{{- if .Values.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Values.genericApp.networkpolicy.namespace }}
  name: {{ .Values.genericApp.networkpolicy.name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.genericApp.name }}
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Values.genericApp.networkpolicy.selectedPodApp1 }}
    - podSelector:
        matchLabels:
          app: {{ .Values.genericApp.networkpolicy.selectedPodApp2 }}
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.genericApp.networkpolicy.namespaceSelector }}
{{- end }}