kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin
  namespace: {{ .Values.namespaces.app }}
  labels:
    app: {{ .Values.labelapp }}
rules:
  - apiGroups: [""] # Indicates the core API group
    resources: ["*"] # All resource within the specified group and namespace
    verbs: ["*"] # All actions
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: visitor
  namespace: {{ .Values.namespaces.app }}
  labels:
    app: {{ .Values.labelapp }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/logs", "services"]
    verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-binding
  namespace: {{ .Values.namespaces.app }}
subjects:
  - kind: User
    name: adrian
    namespace: demo
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: visitor-binding
  namespace: {{ .Values.namespaces.app }}
subjects:
  - kind: User
    name: veronica
    namespace: demo
roleRef:
  kind: Role
  name: visitor
  apiGroup: rbac.authorization.k8s.io