# Admin for the entire Namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role:admin
  namespace: {{ .Values.namespaces.app | quote }}
  labels:
    app: quiz-app
    module: access-control
rules:
- apiGroups: ["", "cert-manager.io", "networking.k8s.io"]
  resources: ["*"]
  verbs: ["*"]

---

# Network developer
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role:network-dev
  namespace: {{ .Values.namespaces.app | quote }}
  labels:
    app: quiz-app
    module: access-control
rules:
# The network developer can only make changes to the network related resources
# While being able to see the pods, pod logs and deployment of the core API group
- apiGroups: ["", "cert-manager.io", "networking.k8s.io"]
  resources: ["services", "ingresses", "networkpolicies", "certificates", "cert-manager", "nodeports", "endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
- apiGroups: [""]
  resources: ["pods", "pod/logs", "deployment"]
  verbs: ["get", "list", "watch"]

---

# Visitor role that is only allowed to see but not change
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role:visitor
  namespace: {{ .Values.namespaces.app | quote }}
  labels:
    app: quiz-app
    module: access-control
rules:
- apiGroups: ["", "networking.k8s.io"]
  resources: ["pods", "pods/logs", "services"]
  verbs: ["get", "list", "watch"]

---

# Set "adrian" as an Admin
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding:admin
  namespace: {{ .Values.namespaces.app | quote }}
  labels:
    app: quiz-app
    module: access-control
subjects:
- kind: User
  name: adrian
  namespace: {{ .Values.namespaces.app | quote }}
roleRef:
  kind: Role
  name: role:admin
  apiGroup: rbac.authorization.k8s.io

---

# Set "nathan" as a Network Developer
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding:network-dev
  namespace: {{ .Values.namespaces.app | quote }}
  labels:
    app: quiz-app
    module: access-control
subjects:
- kind: User
  name: nathan
  namespace: {{ .Values.namespaces.app | quote }}
roleRef:
  kind: Role
  name: role:network-dev
  apiGroup: rbac.authorization.k8s.io

---

# Set "veronica" as a Visitor
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding:visitor
  namespace: {{ .Values.namespaces.app | quote }}
  labels:
    app: quiz-app
    module: access-control
subjects:
- kind: User
  name: veronica
  namespace: {{ .Values.namespaces.app | quote }}
roleRef:
  kind: Role
  name: role:visitor
  apiGroup: rbac.authorization.k8s.io