# Admin for the entire Namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-role
  namespace: {{ .Values.namespaces.app | quote }}
  labels:
    app: quiz-app
    module: access-control
rules:
  - apiGroups: ["", "cert-manager.io", "networking.k8s.io"]
    resources: ["*"]
    verbs: ["*"]

---

# Visitor role that is only allowed to see but not change
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: visitor-role
  namespace: {{ .Values.namespaces.app | quote }}
  labels:
    app: quiz-app
    module: access-control
rules:
  - apiGroups: ["", "networking.k8s.io"]
    resources: ["pods", "pods/logs", "services"]
    verbs: ["get", "list", "watch"]

---

# Set "adrian" as an Admin
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-cluster
  namespace: {{ .Values.namespaces.app | quote }}
  labels:
    app: quiz-app
    module: access-control
subjects:
  - kind: User
    name: adrian
    namespace: {{ .Values.namespaces.app | quote }}
roleRef:
  kind: Role
  name: admin-role
  apiGroup: rbac.authorization.k8s.io

---

# Set "veronica" as a Visitor
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: visitor-binding
  namespace: {{ .Values.namespaces.app | quote }}
  labels:
    app: quiz-app
    module: access-control
subjects:
  - kind: User
    name: veronica
    namespace: {{ .Values.namespaces.app | quote }}
roleRef:
  kind: Role
  name: visitor-role
  apiGroup: rbac.authorization.k8s.io