# Default values for quizAPI.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
enabled: true

replicaCount: 3
labelapp: app
group: app

genericApp:
  name: app-name

  container:
    image: add-image-here
    port: 8080

  service:
    type: ClusterIP
    protocol: TCP
    port: 8080
  
  ingress:
    name: ingress-service
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: serviceName
              servicePort: 8080