apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  namespace: quiz-app
  labels:
    app: nfs
  
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.quiz-app.svc.cluster.local
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs
  namespace: quiz-app
  labels:
    app: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi

