apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: quiz-app
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30001
  selector:
    app: postgres