apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: quiz-app
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: postgres-service