apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-api-deployment
  labels:
    app: quiz-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quiz-api
  template:
    metadata:
      labels:
        app: quiz-api
    spec:
      containers:
      - name: quiz-api-container
        image: localhost:32000/quiz-app:v1
        ports:
        - containerPort: 5000
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            value: 'postgres'
          - name: POSTGRES_HOST
            value: 'localhost'
          - name: POSTGRES_PORT
            value: '5432'
          - name: POSTGRES_USER
            value: 'postgres'