"""added new columns to answer

Revision ID: 67e98998e83e
Revises: 
Create Date: 2024-01-13 13:23:25.135690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e98998e83e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer1', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('answer2', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('answer3', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('answer4', sa.Integer(), nullable=False))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('course',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('course',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('answer4')
        batch_op.drop_column('answer3')
        batch_op.drop_column('answer2')
        batch_op.drop_column('answer1')

    # ### end Alembic commands ###
