"""empty message

Revision ID: 74720e3ef466
Revises: df143f52c38c
Create Date: 2024-01-16 19:24:20.704389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74720e3ef466'
down_revision = 'df143f52c38c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_id', sa.Integer(), nullable=False))
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('answer_id')

    # ### end Alembic commands ###
