"""empty message

Revision ID: a8c7029c9ff0
Revises: f7f3d459734c
Create Date: 2024-01-16 19:47:08.815451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c7029c9ff0'
down_revision = 'f7f3d459734c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
