"""empty message

Revision ID: df143f52c38c
Revises: 67e98998e83e
Create Date: 2024-01-16 18:57:15.013541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df143f52c38c'
down_revision = '67e98998e83e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('is_correct', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('answer3')
        batch_op.drop_column('answer2')
        batch_op.drop_column('answer4')
        batch_op.drop_column('answer1')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])
        batch_op.drop_column('course')
        batch_op.drop_column('answer2')
        batch_op.drop_column('answer3')
        batch_op.drop_column('answer4')
        batch_op.drop_column('answer1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer1', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('answer4', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('answer3', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('answer2', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('course', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('course_id')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer1', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('answer4', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('answer2', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('answer3', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('is_correct')
        batch_op.drop_column('answer')

    # ### end Alembic commands ###
