"""empty message

Revision ID: f7f3d459734c
Revises: df37de7a3b61
Create Date: 2024-01-16 19:45:52.264403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f3d459734c'
down_revision = 'df37de7a3b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
